=== PennyLaneAI/demos/metadata_schemas/demo.metadata.schema.0.1.10.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "demo.metadata.schema.0.1.9.json",
    "title": "Demo Metadata",
    "description": "A demo's metadata",
    "type": "object",
    "properties": {
      "title": {
        "description": "The title of the demo.",
        "type": "string",
        "minLength": 2
      },
      "slug": {
        "description": "The slug of the demo. This should match the base name of the metadata file.",
        "type": "string",
        "minLength": 1
      },
      "executable_stable":{
        "description": "Whether or not the master branch version of this demo is executable.",
        "type": "boolean"
      },
      "executable_latest":{
        "description": "Whether or not the dev branch version of this demo is executable.",
        "type": "boolean"
      },
      "authors": {
        "description": "The author(s) of the demo. This array must contain at least one item.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/author.schema.0.2.0.json"
        },
        "minItems": 1
      },
      "dateOfPublication": {
        "description": "The date on which the demo was first published, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "dateOfLastModification": {
        "description": "The date on which the demo was last modified, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "categories": {
        "description": "An array of the categories that this demo is in.",
        "type": "array",
        "items": {
          "enum": [
            "Algorithms",
            "Getting Started",
            "Optimization",
            "Quantum Machine Learning",
            "Quantum Chemistry",
            "Devices and Performance",
            "Quantum Computing",
            "Quantum Hardware",
            "How-to",
            "Compilation",
            "Resource Estimation",
            "FTQC"
          ]
        },
        "minItems": 1
      },
      "tags": {
        "description": "An array of the tags that the demo has. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "previewImages": {
        "description": "An array of the different images that can be used as previews for this demo - e.g., thumbnails, social media cards (perhaps of different aspect ratios).",
        "type": "array",
        "items": {
          "$ref": "file:./objects/preview.image.schema.0.1.0.json"
        },
        "minItems": 1
      },
      "seoDescription": {
        "description": "A description of the demo suitable for SEO purposes. Ideally this should be less than 150 characters, but this is not a strict limit. It should be a full, grammatically-correct sentence ending in a full stop.",
        "type": "string",
        "minLength": 2
      },
      "doi": {
        "description": "The DOI for the demo.",
        "type": "string",
        "pattern": "^$|^10[.]"
      },
      "references": {
        "description": "An array of the references used for the demo.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/reference.schema.0.1.0.json"
        }
      },
      "basedOnPapers": {
        "description": "An array of the DOIs for the papers the demo is based on. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "referencedByPapers": {
        "description": "An array of the DOIs of any papers that reference the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "relatedContent": {
        "description": "An array of objects describing the content related to the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/related.content.schema.0.1.0.json"
        }
      },
      "hardware": {
        "description": "An array of objects representing third-party vendors who can run the demo on their hardware. An empty array is allowed.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/hardware.schema.0.1.0.json"
        }
      },
      "discussionForumUrl": {
        "description": "Link to dedicated discussion forum thread on https://discuss.pennylane.ai/ for this demo",
        "type": "string",
        "format": "uri",
        "pattern": "(^https?:\/\/(www.)?discuss.pennylane.ai(?:\/.*)?$)"
      }
    },
    "required": [
      "title", "authors", "dateOfPublication", "dateOfLastModification", "categories", "tags", "previewImages", "seoDescription", "doi", "references", "basedOnPapers", "referencedByPapers", "relatedContent"
    ]
  }

=== PennyLaneAI/demos/demonstrations_v2/tutorial_qaoa_maxcut/metadata.json
{
    "title": "QAOA for MaxCut",
    "authors": [
        {
            "username": "alowe"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2019-10-11T00:00:00+00:00",
    "dateOfLastModification": "2026-04-06T00:00:00+00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_QAOA_for_MaxCut.png"
        }
    ],
    "seoDescription": "Implementing the quantum approximate optimization algorithm using PennyLane to solve the MaxCut problem.",
    "doi": "",
    "references": [],
    "basedOnPapers": [
        "10.48550/arXiv.1411.4028"
    ],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_qaoa_intro",
            "weight": 1.0
        }
    ],
    "discussionForumUrl": "https://discuss.pennylane.ai/t/qaoa-and-optimization/5188"
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_iqp_circuit_optimization_jax/metadata.json
{
    "title": "Fast optimization of instantaneous quantum polynomial circuits",
    "authors": [
        {
            "username": "erikrecio"
        },
        {
            "username": "josephbowles"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2025-02-14T09:00:00+00:00",
    "dateOfLastModification": "2026-05-28T00:00:00+00:00",
    "categories": [
        "Optimization",
        "Algorithms"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_iqp_circuit_optimization_jax.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_iqp_circuit_optimization_jax.png"
        }
    ],
    "seoDescription": "Learn how to speed up the optimization of Instantaneous Quantum Polynomial (IQP) circuits using the IQPopt package.",
    "doi": "",
    "references": [
        {
            "id": "bremner1",
            "type": "preprint",
            "title": "Classical simulation of commuting quantum computations implies collapse of the polynomial hierarchy",
            "authors": "Michael J. Bremner, Richard Jozsa, Dan J. Shepherd",
            "year": "2010",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.1005.1407",
            "url": "https://arxiv.org/abs/1005.1407"
        },
        {
            "id": "recio1",
            "type": "preprint",
            "title": "IQPopt: Fast optimization of instantaneous quantum polynomial circuits in JAX",
            "authors": "Erik Recio-Armengol, Joseph Bowles",
            "year": "2025",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2501.04776",
            "url": "https://arxiv.org/abs/2501.04776"
        },
        {
            "id": "bremner2",
            "type": "article",
            "title": "Achieving quantum supremacy with sparse and noisy commuting quantum computations",
            "authors": "Michael J. Bremner, Ashley Montanaro, Dan J. Shepherd",
            "year": "2017",
            "publisher": "",
            "journal": "Quantum",
            "doi": "10.22331/q-2017-04-25-8",
            "url": "https://quantum-journal.org/papers/q-2017-04-25-8/"
        },
        {
            "id": "bluvstein",
            "type": "article",
            "title": "Logical quantum processor based on reconfigurable atom arrays",
            "authors": "Dolev Bluvstein, Simon J Evered, Alexandra A Geim, Sophie H Li, Hengyun Zhou, Tom Manovitz, Sepehr Ebadi, Madelyn Cain, Marcin Kalinowski, Dominik Hangleiter, et al.",
            "year": "2024",
            "publisher": "",
            "journal": "Nature",
            "doi": "10.1038/s41586-023-06927-3",
            "url": "https://www.nature.com/articles/s41586-023-06927-3"
        },
        {
            "id": "nest",
            "type": "preprint",
            "title": "Simulating quantum computers with probabilistic methods",
            "authors": "M. Van den Nest",
            "year": "2010",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.0911.1624",
            "url": "https://arxiv.org/abs/0911.1624"
        },
        {
            "id": "ravuri",
            "type": "preprint",
            "title": "Understanding Deep Generative Models with Generalized Empirical Likelihoods",
            "authors": "Suman Ravuri, M\u00e9lanie Rey, Shakir Mohamed, Marc Deisenroth",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2306.09780",
            "url": "https://arxiv.org/abs/2306.09780"
        },
        {
            "id": "marshall1",
            "type": "preprint",
            "title": "Improved separation between quantum and classical computers for sampling and functional tasks",
            "authors": "Simon C. Marshall, Scott Aaronson, Vedran Dunjko",
            "year": "2024",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2410.20935",
            "url": "https://arxiv.org/abs/2410.20935"
        }
    ],
    "basedOnPapers": [
        "10.48550/arXiv.2501.04776"
    ],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_quantum_gans",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_how_to_import_qiskit_noise_models/metadata.json
{
    "title": "How to import noise models from Qiskit",
    "authors": [
        {
            "username": "whatsis"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2024-11-25T00:00:00+00:00",
    "dateOfLastModification": "2026-05-15T00:00:00+00:00",
    "categories": [
        "Quantum Computing",
        "How-to"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_how_to_import_qiskit_noise_models.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_how_to_import_qiskit_noise_models.png"
        }
    ],
    "seoDescription": "Learn how noise models can be imported into PennyLane from Qiskit.",
    "doi": "",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_how_to_use_noise_models",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_noisy_circuits",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_chemical_reactions/metadata.json
{
    "title": "Modelling chemical reactions on a quantum computer",
    "authors": [
        {
            "username": "vrishi"
        },
        {
            "username": "ixfoduap"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2021-07-23T00:00:00+00:00",
    "dateOfLastModification": "2026-04-10T15:48:14+00:00",
    "categories": [
        "Quantum Chemistry"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_modelling_chemical_reactions_QC.png"
        }
    ],
    "seoDescription": "Construct potential energy surfaces for chemical reactions",
    "doi": "",
    "references": [
        {
            "id": "motta2020",
            "type": "article",
            "title": "A Tale of Colliding Electrons: Boosting the Accuracy of Chemical Simulations on Quantum Computers",
            "authors": "Mario Motta, Tanvi Gujarati, and Julia Rice",
            "year": "2020",
            "journal": "",
            "url": "https://medium.com/qiskit/a-tale-of-colliding-electrons-boosting-the-accuracy-of-chemical-simulations-on-quantum-computers-50a4b4ee5c64"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_quantum_chemistry",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_vqe",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_classical_expval_estimation/metadata.json
{
    "title": "Pauli Propagation: Classically estimating expectation values from parametrized quantum circuits",
    "authors": [
        {
            "username": "dwierichs"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2024-09-10T00:00:00+00:00",
    "dateOfLastModification": "2026-06-01T15:48:14+00:00",
    "categories": [
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_classical_expval_estimation.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_classical_expval_estimation.png"
        }
    ],
    "seoDescription": "Estimate expectation values from parametrized quantum circuits efficiently on average with truncated Pauli propagation.",
    "doi": "",
    "references": [
        {
            "id": "gottesman",
            "type": "article",
            "title": "The Heisenberg Representation of Quantum Computers.",
            "authors": "D. Gottesman",
            "year": "1998",
            "journal": "",
            "url": "https://arxiv.org/abs/quant-ph/9807006"
        },
        {
            "id": "angrisani",
            "type": "article",
            "title": "Classically estimating observables of noiseless quantum circuits.",
            "authors": "Armando Angrisani, Alexander Schmidhuber, Manuel S. Rudolph, M. Cerezo, Zoë Holmes, Hsin-Yuan Huang",
            "year": "2024",
            "journal": "",
            "url": "https://arxiv.org/abs/2409.01706"
        },
        {
            "id": "aharonov",
            "type": "article",
            "title": "A polynomial-time classical algorithm for noisy random circuit sampling.",
            "authors": "Dorit Aharonov, Xun Gao, Zeph Landau, Yunchao Liu, Umesh Vazirani",
            "year": "2022",
            "journal": "",
            "url": "https://arxiv.org/abs/2211.03999"
        },
        {
            "id": "lowesa",
            "type": "article",
            "title": "Classical surrogate simulation of quantum systems with LOWESA.",
            "authors": "Manuel S. Rudolph, Enrico Fontana, Zoë Holmes, Lukasz Cincio",
            "year": "2023",
            "journal": "",
            "url": "https://arxiv.org/abs/2308.09109"
        },
        {
            "id": "begusic",
            "type": "article",
            "title": "Fast and converged classical simulations of evidence for the utility of quantum computing before fault tolerance.",
            "authors": "Tomislav Begušić, Johnnie Gray, Garnet Kin-Lic Chan",
            "year": "2023",
            "journal": "",
            "url": "https://arxiv.org/abs/2308.05077"
        }
    ],
    "basedOnPapers": [
        "10.48550/arXiv.2409.01706"
    ],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_clifford_circuit_simulations",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_liesim",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_qksd_qsp_qualtran/metadata.json
{
    "title": "Using PennyLane and Qualtran to analyze how QSP can improve measurements of molecular properties",
    "authors": [
        {
            "username": "Diego"
        },
        {
            "username": "oumarou"
        },
        {
            "username": "ANT0N"
        },
        {
            "username": "austingmhuang"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2025-08-29T00:00:00+00:00",
    "dateOfLastModification": "2026-06-19T00:00:00+00:00",
    "categories": [
        "Quantum Computing",
        "Resource Estimation"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/pennylane-demo-qualtran-covestro-krylov-subspace-paper-thumbnail.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/pennylane-demo-qualtran-covestro-krylov-subspace-paper-large-thumbnail.png"
        }
    ],
    "seoDescription": "Learn how to obtain reduced density matrices with QKSD and QSP",
    "doi": "",
    "references": [],
    "basedOnPapers": [
        "10.48550/arXiv.2501.05286"
    ],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_how_to_use_qualtran_with_pennylane",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "function_fitting_qsp",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_intro_qsvt",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/circuits_as_fourier_series/metadata.json
{
    "title": "Circuits as Fourier series",
    "authors": [
        {
            "username": "hapax"
        }
    ],
    "executable_stable": false,
    "executable_latest": false,
    "dateOfPublication": "2023-09-11T00:00:00+00:00",
    "dateOfLastModification": "2026-05-15T00:00:00+00:00",
    "categories": [
        "Optimization",
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/circuits_as_fourier_series/thumbnail_circuits_as_fourier_series.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_circuits_as_fourier_series.png"
        }
    ],
    "seoDescription": "Learn with this interactive, code-free introduction to the idea of quantum circuits as Fourier series.",
    "doi": "",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_expressivity_fourier_series",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_general_parshift",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_stochastic_parameter_shift",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_here_comes_the_sun/metadata.json
{
    "title": "Here comes the SU(N): multivariate quantum gates and gradients",
    "authors": [
        {
            "username": "dwierichs"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2023-04-03T00:00:00+00:00",
    "dateOfLastModification": "2026-05-28T00:00:00+00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/here_comes_the_sun/thumbnail_tutorial_here_comes_the_sun.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_here_comes_the_sun.png"
        }
    ],
    "seoDescription": "Learn about multivariate quantum gates for optimization",
    "doi": "",
    "references": [
        {
            "id": "vatan",
            "type": "article",
            "title": "Optimal Quantum Circuits for General Two-Qubit Gates",
            "authors": "Farrokh Vatan and Colin Williams",
            "year": "2003",
            "publisher": "",
            "journal": "",
            "url": "https://arxiv.org/abs/quant-ph/0308006"
        },
        {
            "id": "wiersema",
            "type": "article",
            "title": "Here comes the SU(N): multivariate quantum gates and gradients",
            "authors": "R. Wiersema, D. Lewis, D. Wierichs, J. F. Carrasquilla, and N. Killoran",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "url": "https://arxiv.org/abs/2303.11355"
        },
        {
            "id": "banchi",
            "type": "article",
            "title": "Measuring Analytic Gradients of General Quantum Evolution with the Stochastic Parameter Shift Rule.",
            "authors": "Leonardo Banchi and Gavin E. Crooks",
            "year": "2021",
            "publisher": "",
            "journal": "Quantum",
            "url": "https://quantum-journal.org/papers/q-2021-01-25-386/"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_vqe",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_general_parshift",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_unitary_designs",
            "weight": 1.0
        }
    ]
}
