=== PennyLaneAI/demos/metadata_schemas/demo.metadata.schema.0.1.10.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "demo.metadata.schema.0.1.9.json",
    "title": "Demo Metadata",
    "description": "A demo's metadata",
    "type": "object",
    "properties": {
      "title": {
        "description": "The title of the demo.",
        "type": "string",
        "minLength": 2
      },
      "slug": {
        "description": "The slug of the demo. This should match the base name of the metadata file.",
        "type": "string",
        "minLength": 1
      },
      "executable_stable":{
        "description": "Whether or not the master branch version of this demo is executable.",
        "type": "boolean"
      },
      "executable_latest":{
        "description": "Whether or not the dev branch version of this demo is executable.",
        "type": "boolean"
      },
      "authors": {
        "description": "The author(s) of the demo. This array must contain at least one item.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/author.schema.0.2.0.json"
        },
        "minItems": 1
      },
      "dateOfPublication": {
        "description": "The date on which the demo was first published, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "dateOfLastModification": {
        "description": "The date on which the demo was last modified, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "categories": {
        "description": "An array of the categories that this demo is in.",
        "type": "array",
        "items": {
          "enum": [
            "Algorithms",
            "Getting Started",
            "Optimization",
            "Quantum Machine Learning",
            "Quantum Chemistry",
            "Devices and Performance",
            "Quantum Computing",
            "Quantum Hardware",
            "How-to",
            "Compilation",
            "Resource Estimation",
            "FTQC"
          ]
        },
        "minItems": 1
      },
      "tags": {
        "description": "An array of the tags that the demo has. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "previewImages": {
        "description": "An array of the different images that can be used as previews for this demo - e.g., thumbnails, social media cards (perhaps of different aspect ratios).",
        "type": "array",
        "items": {
          "$ref": "file:./objects/preview.image.schema.0.1.0.json"
        },
        "minItems": 1
      },
      "seoDescription": {
        "description": "A description of the demo suitable for SEO purposes. Ideally this should be less than 150 characters, but this is not a strict limit. It should be a full, grammatically-correct sentence ending in a full stop.",
        "type": "string",
        "minLength": 2
      },
      "doi": {
        "description": "The DOI for the demo.",
        "type": "string",
        "pattern": "^$|^10[.]"
      },
      "references": {
        "description": "An array of the references used for the demo.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/reference.schema.0.1.0.json"
        }
      },
      "basedOnPapers": {
        "description": "An array of the DOIs for the papers the demo is based on. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "referencedByPapers": {
        "description": "An array of the DOIs of any papers that reference the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "relatedContent": {
        "description": "An array of objects describing the content related to the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/related.content.schema.0.1.0.json"
        }
      },
      "hardware": {
        "description": "An array of objects representing third-party vendors who can run the demo on their hardware. An empty array is allowed.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/hardware.schema.0.1.0.json"
        }
      },
      "discussionForumUrl": {
        "description": "Link to dedicated discussion forum thread on https://discuss.pennylane.ai/ for this demo",
        "type": "string",
        "format": "uri",
        "pattern": "(^https?:\/\/(www.)?discuss.pennylane.ai(?:\/.*)?$)"
      }
    },
    "required": [
      "title", "authors", "dateOfPublication", "dateOfLastModification", "categories", "tags", "previewImages", "seoDescription", "doi", "references", "basedOnPapers", "referencedByPapers", "relatedContent"
    ]
  }

=== PennyLaneAI/demos/demonstrations_v2/tutorial_QUBO/metadata.json
{
    "title": "Quadratic Unconstrained Binary Optimization",
    "authors": [
        {
            "username": "alejomonbar"
        }
    ],
    "executable_stable": false,
    "executable_latest": false,
    "dateOfPublication": "2024-02-29T00:00:00+00:00",
    "dateOfLastModification": "2026-05-28T00:00:00+00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/QUBO/thumbnail_QUBO_2024-02-06.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_QuBO_2024-02-06.png"
        }
    ],
    "seoDescription": "Learn how to solve a QUBO problem in a quantum computer.",
    "doi": "",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [],
    "discussionForumUrl": "https://discuss.pennylane.ai/t/quadratic-unconstrained-binary-optimization-qubo-demo/7339"
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_vqe_qng/metadata.json
{
    "title": "Accelerating VQEs with quantum natural gradient",
    "authors": [
        {
            "username": "mli"
        },
        {
            "username": "lbozanic"
        },
        {
            "username": "ssim"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2020-11-06T00:00:00+00:00",
    "dateOfLastModification": "2026-05-28T00:00:00+00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_accelerating_VQEs.png"
        }
    ],
    "seoDescription": "Accelerating variational quantum eigensolvers using quantum natural gradients in PennyLane.",
    "doi": "",
    "references": [
        {
            "id": "stokes2019",
            "type": "article",
            "title": "Quantum Natural Gradient",
            "authors": "Stokes, James, et al.",
            "year": "2019",
            "journal": "",
            "url": "https://arxiv.org/abs/1909.02108"
        },
        {
            "id": "yamamoto2019",
            "type": "article",
            "title": "On the natural gradient for variational quantum eigensolver",
            "authors": "Yamamoto, Naoki",
            "year": "2019",
            "journal": "",
            "url": "https://arxiv.org/abs/1909.05074"
        },
        {
            "id": "peruzzo2014",
            "type": "article",
            "title": "A variational eigenvalue solver on a photonic quantum processor",
            "authors": "Alberto Peruzzo, Jarrod McClean et al.",
            "year": "2014",
            "journal": "Nature Communications",
            "url": "https://www.nature.com/articles/ncomms5213?origin=ppub"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_vqe",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_quantum_natural_gradient",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_coherent_vqls/metadata.json
{
    "title": "Coherent Variational Quantum Linear Solver",
    "authors": [
        {
            "username": "amari"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2019-11-06T00:00:00+00:00",
    "dateOfLastModification": "2026-06-19T00:00:00+00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_coherent_variational_quantum_learner_solver.png"
        }
    ],
    "seoDescription": "This demonstration extends the variational quantum linear solver to solve linear equations defined by a probabilistic coherent operation.",
    "doi": "",
    "references": [
        {
            "id": "BravoPrieto2019",
            "type": "article",
            "title": "Variational Quantum Linear Solver: A Hybrid Algorithm for Linear Systems",
            "authors": "Carlos Bravo-Prieto, Ryan LaRose, Marco Cerezo, Yigit Subasi, Lukasz Cincio, Patrick J. Coles",
            "year": "2019",
            "journal": "",
            "url": "https://arxiv.org/abs/1909.05820"
        },
        {
            "id": "Kothari2014",
            "type": "phdthesis",
            "title": "Efficient algorithms in quantum query complexity",
            "authors": "Robin Kothari",
            "year": "2014",
            "journal": "",
            "url": ""
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_vqls",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_active_volume/metadata.json
{
    "title": "Active volume",
    "authors": [
        {
            "username": "david"
        },
        {
            "username": "dwierichs"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2026-01-21T10:00:00+00:00",
    "dateOfLastModification": "2026-07-14T12:00:00+00:00",
    "categories": [
        "Quantum Computing",
        "Compilation"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/pennylane-demo-active-volume-thumbnail.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/pennylane-demo-active-volume-large-thumbnail.png"
        }
    ],
    "seoDescription": "Learn about active volume and how to compile for an active volume quantum computer.",
    "doi": "",
    "references": [
        {
            "id": "Litinski2022",
            "type": "article",
            "title": "Active volume: An architecture for efficient fault-tolerant quantum computers with limited non-local connections",
            "authors": "Daniel Litinski, Naomi Nickerson",
            "year": "2022",
            "journal": "arXiv",
            "url": "https://arxiv.org/abs/2211.15465"
        },
        {
        "id": "Litinski2018",
        "type": "article",
        "title": "A Game of Surface Codes: Large-Scale Quantum Computing with Lattice Surgery",
        "authors": "Daniel Litinski",
        "year": "2018",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/1808.02892v3"
    },
    {
        "id": "Gidney2018",
        "type": "article",
        "title": "Halving the cost of quantum addition",
        "authors": "Craig Gidney",
        "year": "2018",
        "journal": "Quantum",
        "url": "https://quantum-journal.org/papers/q-2018-06-18-74/"
    },
    {
        "id": "PauliFrame",
        "type": "article",
        "title": "Pauli Frames for Quantum Computer Architectures",
        "authors": "L. Riesebos, X. Fu, S. Varsamopoulos, C. G. Almudever, K. Bertels",
        "year": "2017",
        "journal": "Proceedings of the 54th Annual Design Automation Conference (DAC '17)",
        "url": "https://doi.org/10.1145/3061639.3062300"
    }
    ],
    "basedOnPapers": [
        "10.48550/arXiv.2211.15465"
    ],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_lattice_surgery",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_game_of_surface_codes",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_zx_calculus",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_game_of_surface_codes/metadata.json
{
    "title": "A Game of Surface Codes: Large-Scale Quantum Computing with Lattice Surgery",
    "authors": [
        {
            "username": "Qottmann"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2025-06-02T00:00:00+00:00",
    "dateOfLastModification": "2026-06-05T00:00:00+00:00",
    "categories": [
        "Quantum Computing",
        "Compilation",
        "Algorithms",
        "FTQC"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_game_of_surface_codes.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_game_of_surface_codes.png"
        }
    ],
    "seoDescription": "A game of surface codes: Exploring space-time tradeoffs in surface code based quantum computation.",
    "doi": "",
    "references": [
        {
            "id": "Litinski",
            "type": "preprint",
            "title": "A Game of Surface Codes: Large-Scale Quantum Computing with Lattice Surgery",
            "authors": "Daniel Litinski",
            "year": "2021",
            "publisher": "",
            "journal": "",
            "doi": "10.22331/q-2019-03-05-128",
            "url": "https://arxiv.org/abs/1808.02892"
        }
    ],
    "basedOnPapers": [
        "10.22331/q-2019-03-05-128"
    ],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_toric_code",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_mbqc",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/qrack/metadata.json
{
    "title": "QJIT compilation with Qrack and Catalyst",
    "authors": [
        {
            "username": "dstrano"
        }
    ],
    "executable_stable": false,
    "executable_latest": true,
    "dateOfPublication": "2024-07-10T00:00:00+00:00",
    "dateOfLastModification": "2026-05-25T00:00:00+00:00",
    "categories": [
        "Compilation",
        "Devices and Performance"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_qrack_catalyst_integration.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_qrack_catalyst_integration.png"
        }
    ],
    "seoDescription": "Quantum JIT compilation (QJIT) using the Qrack device for PennyLane and Catalyst, with GPU-acceleration and novel optimization.",
    "doi": "",
    "references": [
        {
            "id": "QECReport",
            "type": "preprint",
            "title": "Exact and approximate simulation of large quantum circuits on a single GPU",
            "authors": "Daniel Strano, Benn Bollay, Aryan Blaauw, Nathan Shammah, William J. Zeng, Andrea Mari",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2304.14969",
            "url": "https://arxiv.org/abs/2304.14969"
        },
        {
            "id": "Wille",
            "type": "preprint",
            "title": "Decision Diagrams for Quantum Computing",
            "authors": "Robert Wille, Stefan Hillmich, Lukas Burgholzer",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2302.04687",
            "url": "https://arxiv.org/abs/2302.04687"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_qft",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_clifford_circuit_simulations",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_mcm_introduction",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_intro_qram/metadata.json
{
    "title": "Intro to quantum random access memory (QRAM)",
    "authors": [
        {
            "username": "dren"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2026-04-23T15:00:00+00:00",
    "dateOfLastModification": "2026-04-23T15:00:00+00:00",
    "categories": [
        "Algorithms",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_qrom.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_qrom.png"
        }
    ],
    "seoDescription": "Learn how to enter data into a quantum computer with a quantum read-only memory (QROM) approach.",
    "doi": "",
    "references": [
        {
            "id": "unary",
            "type": "article",
            "title": "Encoding Electronic Spectra in Quantum Circuits with Linear T Complexity",
            "authors": "Ryan Babbush, Craig Gidney, Dominic W. Berry, Nathan Wiebe, Jarrod McClean, Alexandru Paler, Austin Fowler, Hartmut Neven",
            "year": "2018",
            "publisher": "",
            "journal": "Physical Review X",
            "url": "http://dx.doi.org/10.1103/PhysRevX.8.041015"
        },
        {
            "id": "selectSwap",
            "type": "article",
            "title": "Trading T-gates for dirty qubits in state preparation and unitary synthesis",
            "authors": "Guang Hao Low, Vadym Kliuchnikov, Luke Schaeffer",
            "year": "2018",
            "publisher": "",
            "journal": "arXiv",
            "url": "https://arxiv.org/abs/1812.00954"
        },
        {
            "id": "cleanQROM",
            "type": "article",
            "title": "Qubitization of Arbitrary Basis Quantum Chemistry Leveraging Sparsity and Low Rank Factorization",
            "authors": "Dominic W. Berry, Craig Gidney, Mario Motta, Jarrod R. McClean, Ryan Babbush",
            "year": "2019",
            "publisher": "",
            "journal": "Quantum",
            "url": "http://dx.doi.org/10.22331/q-2019-12-02-208"
        },
        {
            "id": "StatePrep",
            "type": "article",
            "title": "Creating superpositions that correspond to efficiently integrable probability distributions",
            "authors": "Lov Grover, Terry Rudolph",
            "year": "2002",
            "publisher": "",
            "journal": "arXiv",
            "url": "https://arxiv.org/abs/quant-ph/0208112"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_initial_state_preparation",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_kernels_module/metadata.json
{
    "title": "Training and evaluating quantum kernels",
    "authors": [
        {
            "username": "pjderks"
        },
        {
            "username": "pkfaehrmann"
        },
        {
            "username": "egfuster"
        },
        {
            "username": "thubregtsen"
        },
        {
            "username": "jjmeyer"
        },
        {
            "username": "dwierichs"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2021-06-24T00:00:00+00:00",
    "dateOfLastModification": "2026-05-15T00:00:00+00:00",
    "categories": [
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_training_and_evaluating_quantum_kernels.png"
        }
    ],
    "seoDescription": "Kernels and alignment training with Pennylane.",
    "doi": "",
    "references": [
        {
            "id": "Training_QEKs",
            "type": "article",
            "title": "Training Quantum Embedding Kernels on Near-Term Quantum Computers.",
            "authors": "Thomas Hubregtsen, David Wierichs, Elies Gil-Fuster, Peter-Jan H. S. Derks, Paul K. Faehrmann, and Johannes Jakob Meyer",
            "year": "2021",
            "journal": "",
            "url": "https://arxiv.org/abs/2105.02276"
        },
        {
            "id": "Alignment",
            "type": "article",
            "title": "An overview of kernel alignment and its applications.",
            "authors": "Wang, Tinghua, Dongyan Zhao, and Shengfeng Tian",
            "year": "2015",
            "journal": "Artificial Intelligence Review",
            "url": "https://link.springer.com/article/10.1007/s10462-012-9369-4"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_kernel_based_training",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_data_reuploading_classifier",
            "weight": 1.0
        }
    ]
}
